### ISSUE TITLE
Bad link for Apache Spark Redbook

### ISSUE THREAD

**Issue by johnottogood** [IzODA/izODA.github.io#14] opened 2017-10-10 02:37 UTC
https://izoda.github.io/odl/
The above page makes a reference to chapter 3 of "Apache Spark Redbook", referring to it with this URL:
http://www.redbooks.ibm.com/abstracts/sg248325.html5/$file/azk1c100.pdf

The redbook site indicates that is an invalid URL

Is this the desired Redbook? 
http://www.redbooks.ibm.com/redbooks/pdfs/sg248325.pdf    (Apache Spark Implementation on IBM z/OS)

**Comment by ytang327** [comment] 2017-10-12 18:25
Yes, it is. Thanks for the catch. The issue is addressed in PR #15

**Closed** 2017-10-23 14:10 UTC
